# Generated by Django 4.2.7 on 2024-01-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
